name: datn_mobile
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.8.0"

dependencies:
  auto_route: ^10.1.2
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  hive_ce_flutter: ^2.3.2
  internet_connection_checker_plus: ^2.8.0
  intl: ^0.20.2
  multiple_result: ^5.2.0
  path_provider: ^2.1.5
  platform_info: ^5.0.0
  responsive_framework:
    git: https://github.com/Shreemanarjun/ResponsiveFramework.git
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  talker_dio_logger: ^4.9.3
  talker_flutter: ^4.9.3
  flutter_hooks: ^0.21.3
  json_annotation: ^4.9.0
  retrofit: ^4.7.2
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  shadcn_ui: ^0.31.8
  lucide_icons_flutter: ^3.1.8
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  loading_overlay: ^0.5.0
  device_info_plus: ^12.1.0
  intl_phone_number_input: ^0.7.5
  auth_buttons: ^3.0.3
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  app_links: ^6.4.1
  flutter_web_auth_2: ^4.1.0
  flutter_secure_storage: ^9.2.4
  infinite_scroll_pagination: ^5.1.1
  wolt_modal_sheet: ^0.11.0
  markdown_editor_plus: ^0.2.15
  gal: ^2.3.2
  cached_network_image: ^3.4.1
  uuid: ^4.1.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1
  timeago: ^3.7.0
  flutter_quill: ^11.5.0
  markdown_quill: ^4.3.0
  flex_dropdown: ^0.1.0
  freezed: ^3.2.3
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^3.0.0-dev.17
  slang_build_runner: ^4.8.1
  spot: ^0.16.0
  very_good_analysis: ^9.0.0
  json_serializable: ^6.11.1
  retrofit_generator: ^10.0.0
  flutter_pre_commit: ^0.2.4
  dart_quill_delta: ^10.8.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/providers/
    - .env
